### ISSUE TITLE
Using autoform with Mongol flashes the previous value when saving a record.

### ISSUE THREAD

**Issue by wesyah234** [msavin/Mongol#84] opened 2015-04-29 21:41 UTC
This is odd, I recorded it as a screencast... the previous value of the document flashes on the screen when saving a record.  I'm using autoform.

http://screencast-o-matic.com/watch/cofUr4feIz

Oddly, this seems to be intermittent because I'm trying it again and now I can't get it to happen... nothing was changed in the code... so it's probably not a big deal... especially since one wouldn't be using mongol in production, I just wanted to let you know what I saw.

**Comment by JackAdams** [comment] 2015-04-30 08:29
Very odd. I can't immediately see what might be causing that, but then I'm not too familiar with the autoform internals.

**Comment by msavin** [comment] 2015-06-04 02:15
Can you confirm if this is for a specific browser or just an overall issue?

**Comment by msavin** [comment] 2015-07-04 18:27
Closing since there is no reproduction

**Closed as completed by msavin** 2015-07-04 18:27 UTC
