### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by isAlmogK** [msavin/Mongol#67] opened 2015-03-28 00:53 UTC
I'm getting the following error message after installing 

 Uncaught TypeError: Cannot read property 'find' of undefined editable-json-client.js:143

**Comment by JackAdams** [comment] 2015-03-28 13:22
Any chance you can put up a minimal repro?  I should be able to fix this if I know what I'm looking for.

**Comment by isAlmogK** [comment] 2015-03-31 08:32
I'm not sure a minimal repro will recreate the issue I think it's a conflict within my app / packages that I'm using

**Comment by JackAdams** [comment] 2015-03-31 09:05
I've just committed a possible fix/workaround for this (or at least what I think is causing this). Will hopefully make it into the next release.

**Comment by isAlmogK** [comment] 2015-03-31 09:08
Ok let me know when it's out I will test it

**Comment by JackAdams** [comment] 2015-03-31 09:17
That's up to @msavin.  Fair warning though, the fix should allow Mongol to run, but expect some weird behaviour.  I really need to know a bit more about the packages you are using to try and figure out the root cause. (A copy of the `.meteor/packages.js` file from your app would be great for this.)

**Comment by isAlmogK** [comment] 2015-03-31 09:20
No problem 

meteor-platform
accounts-password
iron:router
jquery
appcache
alanning:roles
audit-argument-checks
multiply:iron-router-progress
underscore

natestrauser:select2
tsega:bootstrap3-datetimepicker
momentjs:moment
ground:db
joshowens:accounts-entry
twbs:bootstrap
harrison:papa-parse
matteodem:easy-search
ongoworks:pdf
underscorestring:underscore.string
matb33:collection-hooks
wylio:mandrill
percolatestudio:segment.io@=1.1.0_1
gadicohen:messageformat
amplify
sacha:spin
meteorhacks:kadira@2.20.1

**Comment by msavin** [comment] 2015-04-26 20:13
Following up

**Closed as completed** 2015-05-15 16:31 UTC
