### ISSUE TITLE
No such template error in console

### ISSUE THREAD

**Issue by ryanbuiltthat** [msavin/Mongol#75] opened 2015-04-11 16:18 UTC
When invoking mongol on my app I get the following error in the console...

```
Error: No such template: MeteorToys_accounts
    at Blaze.View.lookup (lookup.js:122)
    at null.<anonymous> (spacebars-runtime.js:30)
    at view.js:191
    at Function.Template._withTemplateInstanceFunc (template.js:437)
    at view.js:190
    at Object.Blaze._withCurrentView (view.js:523)
    at viewAutorun (view.js:189)
    at Tracker.Computation._compute (tracker.js:294)
    at new Tracker.Computation (tracker.js:210)
    at Object.Tracker.autorun (tracker.js:533)
```

It still seems to work though and nothing breaks the functionality so is this something I should just ignore or am I breaking something?

**Comment by abernix** [comment] 2015-04-12 15:42
Duplicate of #74, but also happening to me.

**Comment by msavin** [comment] 2015-04-24 05:02
Fixed and verified in new update

**Closed as completed by msavin** 2015-04-24 05:02 UTC
