### ISSUE TITLE
Application crashes when msavin:mongol installed (resolves when removed)

### ISSUE THREAD

**Issue by gsovereignty** [msavin/Mongol#114] opened 2015-09-30 01:15 UTC
See: https://github.com/gazhayes/popvote for relevant full code to replicate.

=> Exited with code: 8  
W20150930-08:59:17.902(8)? (STDERR) 
W20150930-08:59:17.903(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-08:59:17.903(8)? (STDERR)                             throw(ex);
W20150930-08:59:17.903(8)? (STDERR) /Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-08:59:17.903(8)? (STDERR)                                   ^
W20150930-08:59:17.904(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-08:59:17.904(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-08:59:17.904(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150930-08:59:17.904(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150930-08:59:17.904(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:242:10
W20150930-08:59:17.904(8)? (STDERR)     at Array.forEach (native)
W20150930-08:59:17.904(8)? (STDERR)     at Function._.each._.forEach (/Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-08:59:17.905(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:137:5
W20150930-08:59:21.525(8)? (STDERR)  
W20150930-08:59:21.526(8)? (STDERR) /Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-08:59:21.526(8)? (STDERR)                         throw(ex);
W20150930-08:59:21.526(8)? (STDERR)                               ^
W20150930-08:59:21.530(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-08:59:21.530(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-08:59:21.530(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-08:59:21.530(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150930-08:59:21.530(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150930-08:59:21.530(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:242:10
W20150930-08:59:21.531(8)? (STDERR)     at Array.forEach (native)
W20150930-08:59:21.531(8)? (STDERR)     at Function._.each._.forEach (/Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-08:59:21.531(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150930-08:59:24.833(8)? (STDERR)  
W20150930-08:59:24.833(8)? (STDERR) /Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150930-08:59:24.833(8)? (STDERR)                         throw(ex);
W20150930-08:59:24.833(8)? (STDERR)                               ^
W20150930-08:59:24.838(8)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20150930-08:59:24.838(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20150930-08:59:24.838(8)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20150930-08:59:24.838(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20150930-08:59:24.838(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20150930-08:59:24.838(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:242:10
W20150930-08:59:24.838(8)? (STDERR)     at Array.forEach (native)
W20150930-08:59:24.838(8)? (STDERR)     at Function._.each._.forEach (/Users/gareth/.meteor/packages/meteor-tool/.1.1.9.1396jov++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-08:59:24.839(8)? (STDERR)     at /Users/gareth/git/popvote/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by steinitz-zz** [comment] 2015-09-30 02:57
I confirm this behavior with my Meteor 1.2 apps.

**Comment by poyi** [comment] 2015-09-30 06:25
Same here with Meteor 1.2.0.2

**Comment by ziedmahdi** [comment] 2015-09-30 07:15
The problem is with the meteortoys:toykit package which is automatically installed with the mongol package. 

I think that this happens only with the latest version of the meteortoys:toykit package. 

Just install a previous version of this package.

`meteor add msavin:mongol@=1.1.5`

**Comment by zhaoyao91** [comment] 2015-09-30 07:49
@ziedmahdi this can be a temp fix, but I hope it can be fixed in the right way

**Comment by msavin** [comment] 2015-09-30 23:30
Thanks for letting me know. It's fixed in new update. To fix, add and then remove

**Closed as completed by msavin** 2015-09-30 23:30 UTC
