### ISSUE TITLE
Ctrl + M not working in Mac Chrome browser

### ISSUE THREAD

**Issue by lesliechw** [msavin/Mongol#139] opened 2016-09-02 12:06 UTC
Any advice? Never able to load up Mongol. Please advice, thank you.

**Comment by webmagnets** [comment] 2016-09-22 12:19
I am having the same issue.

**Comment by webmagnets** [comment] 2016-09-22 13:23
I was having this problem, but now it resolved itself. Are you still experiencing the issue?

**Comment by msavin** [comment] 2016-11-15 14:54
@lesliechw bump.

There was like a buggy Chrome release, maybe that was it?

**Comment by msavin** [comment] 2017-02-06 22:50
Closing this issue as I have heard about it and am not able to reproduce. If you issue is still recurring, please let me now.

**Closed as completed by msavin** 2017-02-06 22:50 UTC
