### ISSUE TITLE
JSON circular structure error

### ISSUE THREAD

**Issue by wallslide** [msavin/Mongol#28] opened 2015-02-27 06:28 UTC
I get the following error when trying to use a collection of mine (Orders):

```
Exception in template helper: TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at String.Template.MongoInspector_documentViewer.helpers.documentJSON (http://0.0.0.0:3000/packages/msavin_mongol.js?558950870b2ec9c51c4caac919a2ca3b3e8b6a76:540:36)
    at bindDataContext (http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16)
    at Blaze._wrapCatchingExceptions (http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16)
    at Object.Spacebars.call (http://0.0.0.0:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at http://0.0.0.0:3000/packages/msavin_mongol.js?558950870b2ec9c51c4caac919a2ca3b3e8b6a76:467:24
    at null.<anonymous> (http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2472:44)
    at http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1808:16
    at Object.Blaze._withCurrentView (http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
    at viewAutorun (http://0.0.0.0:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1807:18)
```

An instance of the Orders collection has an array in it like this:

``` javascript
{
    lineItems: []
}
```

I use a transform function which puts a reference to the Order itself in each of the lineItems in that array. I either need a way to prevent Mongol from using transformed-objects, or a way to delete that reference before Mongol attempts to use the objects for display.

**Comment by JackAdams** [comment] 2015-02-27 12:56
JSON.stringify is the way that Mongol represents the data in html (using `pre` tags).  I can't think of a way to automatically detect circular references in a transformed document and remove them (because that's certainly what you'd have to do to get it to work).  If you've got a lightweight function that can do that, I can work it into a PR.

**Comment by krawalli** [comment] 2015-02-27 13:08
Maybe you should replate JSON with EJSON. --> http://docs.meteor.com/#/full/ejson_stringify
Didn't test if they have integrated a test for that.

**Comment by JackAdams** [comment] 2015-02-27 13:43
Good thought, but I just tried it with EJSON.stringify and it still throws the error `InternalError: too much recursion`.

I couldn't see any EJSON methods that might help with this, just by typing `EJSON.` in the browser console and seeing what's there, but haven't researched it any further than that.

**Comment by krawalli** [comment] 2015-02-27 15:41
to detect the cause you could iterate over the object with _.each and partitialy stringify the first level properties.

**Comment by JackAdams** [comment] 2015-02-28 00:37
Interesting discussion related to this happening in [one of Meteor's issues #3783](https://github.com/meteor/meteor/issues/3783).  Actually, no. Got the wrong issue. This discussion is related to #16, which is closed(ish).

**Comment by wallslide** [comment] 2015-02-28 01:02
I don't need the package to do it for me necessarily, I just need a hook somewhere that I could fix the problem myself before passing the object off to Mongol.

**Comment by JackAdams** [comment] 2015-02-28 01:14
Okay, cool. What sort of hook? How does `Mongol.beforeInsert = function () { ... }`, `Mongol.beforeUpdate = function () { ... }` sound?

**Comment by wallslide** [comment] 2015-02-28 02:13
In my particular case, I need a hook between when Mongol retrieves the object from the collection, and when displaying it in the UI. Maybe something similar to [AutoForm hooks](https://github.com/aldeed/meteor-autoform#callbackshooks) like:

``` javascript
Mongol.hooks({
  collectionName:{
    before: {
      display: function(document){
        //modify document to get rid of circular reference
        return modifiedDocument;
      }
    }
  }
});
```

**Comment by JackAdams** [comment] 2015-02-28 02:31
Ah, yes. Sorry, I wasn't thinking clearly about the issue you described.  Got it now.  I'll take a look at how autoform does it and have a think about how we can implement this in Mongol.

**Comment by msavin** [comment] 2015-03-12 23:13
Assuming this is fixed. Please let us know if you still have issues.

PS: be sure to run "meteor update" :)

**Comment by JackAdams** [comment] 2015-03-12 23:20
No this one isn't fixed yet.

**Comment by Maxhodges** [comment] 2015-03-13 08:40
This is affecting me too. Same problem as @wallslide. We have a parent-child relationship where the child has a reference to the parent.

Cheers!

**Comment by msavin** [comment] 2015-04-24 03:47
Should be fixed in the upcoming version. More information: https://github.com/msavin/Mongol/issues/77

**Comment by msavin** [comment] 2015-04-25 03:50
@Maxhodges @wallslide please update and let me know if it worked :)

**Comment by wallslide** [comment] 2015-04-28 02:17
@msavin Thanks for the progress. I tried out the latest version, but we've recently moved many of our collections into packages, and now they don't even show up in Mongol's list: https://github.com/msavin/Mongol/issues/83 so I haven't been able to test out if the new changes fixed our problem or not.

**Comment by msavin** [comment] 2015-04-28 02:34
Can you try listing them manually and see how it works? Thanks!

https://github.com/msavin/Mongol/blob/master/documentation/COMPATIBILITY.md

**Comment by msavin** [comment] 2015-05-15 16:30
I'm assuming this is working now since it seems to have been a transform-related issue. Please let me know in the next 7 days or I'll have to assume its no longer an issue.

**Closed as completed** 2015-06-01 20:38 UTC
